### ISSUE TITLE
Fails to play some .mp3 files

### ISSUE THREAD

**Issue by electron0zero** [ProjectRecommend/Recommend#2]
Player is skipping some .mp3 files from playlist, it skips to next song when i double click on it to play.
- OS - Windows 10 64 bit
- version -  under dev. (pre alpha )
- steps to reproduce - unknown

**Comment by electron0zero** [comment]
Probably this is codec issue
it's an issue in Qt Media Player. [Here is Link to Qt Bug Report](https://bugreports.qt.io/browse/QTBUG-51692) 

## Fix - To fix you have to install proper codecs.
LAVFilters seems to fix that for me.
[here is link to LAVFilters releases](https://github.com/Nevcairiel/LAVFilters/releases/)
get the latest releases

here is some suggested ones from Qt Issue tracker

[LAV Splitter](https://1f0.de/lav-splitter/)
[Haali Media Splitter](https://haali.su/mkv/)
[Here's another one](http://www.gdcl.co.uk/mpeg4/)
As you can see there are plenty of options, and I only listed the main ones

**Comment by RiflerRick** [comment]
i got this error too: `DirectShowPlayerService::doRender: Unresolved error code 0x80040266 (IDispatch error #102)`
