### ISSUE TITLE
songPath value not getting updated during metadata updation

### ISSUE THREAD

**Issue by RiflerRick** [ProjectRecommend/Recommend#3]
code:
`currentSongPath = self.mediaPlayer.currentMedia().canonicalUrl().toString()
        self.metadataDialog.songPath = currentSongPath[8:]
        print(self.metadataDialog.songPath)
        metadata = ManageMetaData.ReadMetaData(self, self.metadataDialog.songPath)`
here self.metadataDialog.songPath is not getting updated , it is showing the playlist's first songPath while trying to update metadata of another song

**Comment by RiflerRick** [comment]
okay, so you need to literally play the song to get the songPath updated

**Comment by RiflerRick** [comment]
finally figured the problem out, as long as the song is active(paused or being played) you cannot change its metadata, i tried hard coding the path of a different song in the playlist and it worked

**Comment by electron0zero** [comment]
got it, so we need to get the path of file selected in playlist and also reject the file that is currently being played, otherwise we will get permission denied error because that file is already open and we can't open an already file to edit it's metadata
