### ISSUE TITLE
App crashes on selecting folder with no songs in it

### ISSUE THREAD

**Issue by RiflerRick** [ProjectRecommend/Recommend#7]
### Expected Behavior

May simply show a warning message notifying the user that the folder did not contain any songs

### Actual behavior

The app crashes when the user selects a folder with no songs in it.

### Steps to reproduce behavior

simply go to add songs and add a folder without any songs in it

**Comment by electron0zero** [comment]
@RiflerRick i can't reproduce this issue, can you please send me Trackback if you can reproduce this issue.

**Comment by RiflerRick** [comment]
okay, seems like I also can't reproduce the problem. @raghavmittal101 told me that this was happening but that was some time, now I guess it has been fixed
