### ISSUE TITLE
App crashes on deleting a song from the folder whose songs have been populated on the playlist

### ISSUE THREAD

**Issue by RiflerRick** [ProjectRecommend/Recommend#8]
### Expected behavior

App should simply remove a file from the playlist, if it finds that there are no files of that name anymore

### Actual behavior

app crashes if that file(that is loaded in the app) is deleted

### Steps to reproduce behavior

Simply populate the playlist with songs delete a song from that directory, app will crash with error on the console.

**Comment by electron0zero** [comment]
@RiflerRick can you review this path and just to make sure confirm that's it fixed and you can't reproduce.
